language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t davidcorney/docker-react -f Dockerfile.dev .

script:
  - docker run davidcorney/docker-react npm run test -- --coverage
